### PR TITLE
removed _Names footprints and removed _Numbers in footprints

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by Shackmeister** [comment]
updated L8
l8

**Comment by evanshultz** [comment]
@Shackmeister 
Thanks for putting in the effort to work on these!

A few comments:
1. All footprints should have the format "DirectFET_xx" where "xx" is the can size ("L8", "MZ", "SH", etc.).
1. All footprints start with "IR-", but that should be removed. International Rectifier was purchased by Infineon and also this package was used by multiple vendors anyway.
1. Along with the above, capitalize the "D" in "DirectFET" for footprint and 3D model names. "ME" is OK.
1. Remove the "-Outline" in all footprint names.
1. Please see if the above will affect any 3D models and, if you can, correct them.
1. It appears some footprint names are out-of-sync with the file name, which can be corrected when doing the above:
image
1. For the L8 package you consolidated the pin numbers to only 1-3, which is correct. Can you do the others? For example, the MN can is still using pin numbers up to 7 and so it won't work with our standard FET symbol which has only pins 1, 2, and 3. See https://www.infineon.com/dgdl/irf6646pbf.pdf?fileId=5546d462533600a4015355ec5f071a55 for this footprint.
1. If you're particularly saucy about updating this library, you could confirm all footprints are built to the datasheet. For this library I wouldn't be surprised if there are errors. This is optional, of course.

And one specific comment about the L8 can: there are some weird angles there. Would it be possible/better to round them to exactly 65 degrees?

Thanks again!

**Comment by Shackmeister** [comment]
I agree with everything you said :)
Im gonna go through each footprint (and probably make it completely from scratch), I just started out with the L8 can. The silkscreen angles is to make it match the clearance of the pads.
Regarding 3D models im gonna remake all of them anyway (the wings ones looks horrible anyway)

**Comment by Shackmeister** [comment]
the script still needs some tweeking but here is a small preview :)
directfet_l8_1
directfet_l8_2

**Comment by Shackmeister** [comment]
directfet_l8

**Comment by Shackmeister** [comment]
directfet_mn

**Comment by Shackmeister** [comment]
directfet_mt

**Comment by SchrodingersGat** [comment]
Hi @Shackmeister anything left to work on for this PR or should I give it a review?

**Comment by Shackmeister** [comment]
@SchrodingersGat Im roughly halfway through remaking the footprints.. If you want you are very welcome to review the footprints which has been remade

**Comment by Shackmeister** [comment]
@SchrodingersGat @evanshultz Hi guys, this is now ready for review but not merge. 
the 3D models are still needed before merge, but my 3D script is complete I just need to fill in the parameters :)

**Comment by SchrodingersGat** [comment]
I'm happy with this - let me know when you've got the 3D models ready

**Comment by Shackmeister** [comment]
sooo libraryname got changed?

**Comment by Shackmeister** [comment]
added 3D models here:
https://github.com/KiCad/kicad-library/pull/1735
and
https://github.com/KiCad/kicad-packages3D/pull/143

**Comment by Shackmeister** [comment]
this is now ready to merge if done together with the new 3D models :)
there are still plenty of other DirectFET footprints missing in case somebody should feel like making them

**Comment by poeschlr** [comment]
Off Topic:
@Shackmeister it might be a good idea to use the mail address connected to your current account in your local git setup. (github thinks that DasFrank made  all the contributions. This will confuse the CLA bot.)
Use `git config --global user.email "email@example.com"` to set it globally. You can also set it per repo.

If DasFrank uses the same mail address as your current account then we might need to look into this in more detail.

**Comment by SchrodingersGat** [comment]
These look good, thanks :)

**Pull request merged**
